openapi: "3.0.2"
info:
    title: Reset Password API
    version: "1.0"
    contact:
        name: "Rizjami Putera"
        email: "rizjamiputera@gmail.com"
        url: "https://udaputera.com"
servers:
  - description: Reset Password API
    url: "{url}:5000/v1"
    variables:
        url:
            default: "http://localhost:5000"
paths:
    "/reset_password":
        post:
            tags:
            - Reset Password
            description: Public change password. Reset token will be send to email. Token expired 24 hours
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                email:
                                    type: string
                                    format: email
            responses:
                204:
                    description: OK. No Content
                400:
                    description: Bad Request
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    message:
                                        type: string
                                        example: Email is not valid
                                    error:
                                        type: string
                                        example: Bad Request
                                    statusCode:
                                        type: number
                                        example: 400
                404:
                    description: Bad Request
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    message:
                                        type: string
                                        example: Email is not registered.
                                    error:
                                        type: string
                                        example: Not Found
                                    statusCode:
                                        type: number
                                        example: 404
    "/reset_password/:token":
        post:
            tags:
            - Reset Password
            description: Public Do reset password. Get user by token
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                password:
                                    type: string
                                    format: password
                                confirm_password:
                                    type: string
                                    format: password
            responses:
                204:
                    description: OK. No Content
                400:
                    description: Bad Request
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    message:
                                        type: string
                                        example: Password confirm is not match
                                    error:
                                        type: string
                                        example: Bad Request
                                    statusCode:
                                        type: number
                                        example: 400
                403:
                    description: Forbidden
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    message:
                                        type: string
                                        example: Token already expired
                                    error:
                                        type: string
                                        example: Forbidden
                                    statusCode:
                                        type: number
                                        example: 403
components:
    examples:
        auth:
            summary: auth
            value:
                access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZjI3OGQ4NS1kNDg2LTQ3NGYtOWIyZi03ZDNkNGQ5NDhjYzEiLCJ1c2VybmFtZSI6InVkYV9zdXBlckBnbWFpbC5jb20iLCJyb2xlIjoiU1VQRVJVU0VSIiwiaWF0IjoxNzEwMjk5MTc5LCJleHAiOjE3MTAzODU1Nzl9.BqMYxl56GW7rBi1fYn-NLf7EIVMB7ACtKnB2K-M2fGg
                exp: 1710385579608
                user:
                    id: "591c6b44-9331-4fa0-95a5-1dddc617a033"
                    email: "john_doe@gmail.com"
                    firstname: "John"
                    lastname: "Doe"
                    active: true
                    verified: true
                    avatar: "/public/profile/avatar.jpg"
                    avatar_md: "/public/profile/avatar_md.jpg"
                    role: "MEMBER"
                    taaruf_status: "BLOCKED"
        profile-data:
            summary: profile-data
            value:
                id: "591c6b44-9331-4fa0-95a5-1dddc617a033"
                email: "john_doe@gmail.com"
                firstname: "John"
                lastname: "Doe"
                active: true
                verified: true
                avatar: "/dummy/abang.png"
                avatar_md: "/dummy/abang.png"
                role: "MEMBER"
                taaruf_status: "BLOCKED"
        profile-no-avatar:
            summary: profile-no-avatar
            value:
                id: "591c6b44-9331-4fa0-95a5-1dddc617a033"
                email: "john_doe@gmail.com"
                firstname: "John"
                lastname: "Doe"
                active: true
                verified: true
                avatar: null
                avatar_md: null
                role: "MEMBER"
                taaruf_status: "BLOCKED"

