openapi: "3.0.2"
info:
    title: User Admin API
    version: "1.0"
    contact:
        name: "Rizjami Putera"
        email: "rizjamiputera@gmail.com"
        url: "https://udaputera.com"
servers:
  - description: User Admin API
    url: "{url}:5000/v1"
    variables:
        url:
            default: "http://localhost:5000"
paths:
    "/user-admin":
        post:
            tags:
            - Admin User
            description: Create admin user, Only Role SuperAdmin or Admin can do this
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                firstname:
                                    type: string
                                lastname:
                                    type: string
                                email:
                                    type: string
                                    format: email
                                password:
                                    type: string
                                    format: password
                                confirm_password:
                                    type: string
                                    format: password
            responses:
                200:
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: object
                                $ref: "#/components/schemas/user"
                            examples:
                                user:
                                    $ref: "#/components/examples/new-user"
                400:
                    description: Bad Request
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    message:
                                        type: string
                                        example: Email is invalid
                                    error:
                                        type: string
                                        example: Bad Request
                                    statusCode:
                                        type: number
                                        example: 400
                401:
                    description: Unauthorized
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    error:
                                        type: string
                                        example: Unauthorized
                                    statusCode:
                                        type: number
                                        example: 401
                403:
                    description: Forbidden
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    error:
                                        type: string
                                        example: Forbidden
                                    statusCode:
                                        type: number
                                        example: 403
        get:
            tags:
            - Admin User
            description: Get all admin user, Only Role SuperAdmin or Admin can do this
            responses:
                200:
                    description: "OK"
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: "#/components/schemas/user"
                            examples:
                                example1:
                                    summary: Example 1
                                    value:
                                      - id: "591c6b44-9331-4fa0-95a5-1dddc617a033"
                                        email: "joh@example.com"
                                        firstname: "John"
                                        lastname: "Doe"
                                        active: true
                                        verified: true
                                        avatar: "/avatar/john.jpg"
                                        avatar_md: "/avatar/john_md.jpg"
                                        role: "ADMIN"
                                      - id: "591c6b44-9331-4fa0-95a5-1dddc617a033"
                                        email: "joh@example.com"
                                        firstname: "John"
                                        lastname: "Doe"
                                        active: true
                                        verified: true
                                        avatar: null
                                        avatar_md: null
                                        role: "ADMIN"
                                      - id: "591c6b44-9331-4fa0-95a5-1dddc617a033"
                                        email: "joh@example.com"
                                        firstname: "John"
                                        lastname: "Doe"
                                        active: false
                                        verified: true
                                        avatar: null
                                        avatar_md: null
                                        role: "ADMIN"
    "/user-admin/:id":
        get:
            tags:
            - Admin User
            description: Get by id - Only Role SuperAdmin or Admin can do this
            responses:
                200:
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: object
                                $ref: "#/components/schemas/user"
                            examples:
                                complete-data:
                                    $ref: "#/components/examples/complete-data"
                                no-avatar:
                                    $ref: "#/components/examples/no-avatar"
                401:
                    description: Unauthorized
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    error:
                                        type: string
                                        example: Unauthorized
                                    statusCode:
                                        type: number
                                        example: 401
                403:
                    description: Forbidden
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    error:
                                        type: string
                                        example: Forbidden
                                    statusCode:
                                        type: number
                                        example: 403
        delete:
            tags:
            - Admin User
            description: Only Role SuperAdmin or Admin can do this. Only set active to false
            requestBody:
                required: true
                content:
                    multipart/form-data:
                        schema:
                            type: object
                            properties:
                                firstname:
                                    type: string
                                lastname:
                                    type: string
                                avatar:
                                    type: string
                                    format: binary
            responses:
                200:
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: object
                                $ref: "#/components/schemas/user"
                            examples:
                                complete-data:
                                    $ref: "#/components/examples/complete-data"
                                no-avatar:
                                    $ref: "#/components/examples/no-avatar"
                401:
                    description: Unauthorized
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    error:
                                        type: string
                                        example: Unauthorized
                                    statusCode:
                                        type: number
                                        example: 401
                403:
                    description: Forbidden
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    error:
                                        type: string
                                        example: Forbidden
                                    statusCode:
                                        type: number
                                        example: 403
                404:
                    description: Not Found
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    error:
                                        type: string
                                        example: Not Found
                                    statusCode:
                                        type: number
                                        example: 404
components:
    schemas:
        user:
            type: object
            properties:
                id:
                    type: string
                    example: 591c6b44-9331-4fa0-95a5-1dddc617a033
                email:
                    type: string
                    example: joh...
                firstname:
                    type: string
                    example: Joh...
                lastname:
                    type: string
                    example: Doe...
                active:
                    type: boolean
                    example: true
                verified::
                    type: boolean
                    example: true
                avatar:
                    type: string
                    example: /avatar/myavatar.jpg
                avatar_md:
                    type: string
                    example: /avatar/myavatar.jpg
                role:
                    type: string
                    example: MEMBER
    examples:
        complete-data:
            summary: complete-data
            value:
                id: "591c6b44-9331-4fa0-95a5-1dddc617a033"
                email: "joh@example.com"
                firstname: "John"
                lastname: "Doe"
                active: true
                verified: true
                avatar: "/avatar/john.jpg"
                avatar_md: "/avatar/john_md.jpg"
                role: "ADMIN"
        no-avatar:
            summary: no-avatar
            value:
                id: "591c6b44-9331-4fa0-95a5-1dddc617a033"
                email: "joh@example.com"
                firstname: "John"
                lastname: "Doe"
                active: true
                verified: true
                avatar: null
                avatar_md: null
                role: "ADMIN"
        new-user:
            summary: new-user
            value:
                id: "591c6b44-9331-4fa0-95a5-1dddc617a033"
                email: "joh@example.com"
                firstname: "John"
                lastname: "Doe"
                active: true
                verified: false
                avatar: null
                avatar_md: null
                role: "ADMIN"
