openapi: "3.0.2"
info:
    title: User API
    version: "1.0"
    contact:
        name: "Rizjami Putera"
        email: "rizjamiputera@gmail.com"
        url: "https://udaputera.com"
servers:
  - description: User API
    url: "{url}:5000/v1"
    variables:
        url:
            default: "http://localhost:5000"
paths:
    "/users":
        post:
            tags:
            - User
            description: Create user role as MEMBER
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                firstname:
                                    type: string
                                lastname:
                                    type: string
                                email:
                                    type: string
                                    format: email
                                password:
                                    type: string
                                    format: password
                                confirm_password:
                                    type: string
                                    format: password
            responses:
                200:
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: object
                                $ref: "#/components/schemas/user"
                            examples:
                                user:
                                    $ref: "#/components/examples/user"
                400:
                    description: Bad Request
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    message:
                                        type: string
                                        example: Email is invalid
                                    error:
                                        type: string
                                        example: Bad Request
                                    statusCode:
                                        type: number
                                        example: 400
        get:
            tags:
            - User
            description: Get all user role as MEMBER
            responses:
                200:
                    description: "OK"
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: "#/components/schemas/user"
                            examples:
                                example1:
                                    summary: Example 1
                                    value:
                                      - id: "591c6b44-9331-4fa0-95a5-1dddc617a033"
                                        email: "jo..."
                                        firstname: "Jo..."
                                        lastname: "Do..."
                                        active: true
                                        verified: false
                                        role: "MEMBER"
                                        taaruf_status: "OPEN"
                                      - id: "591c6b44-9331-4fa0-95a5-1dddc617a033"
                                        email: "jo..."
                                        firstname: "Jo..."
                                        lastname: "Do..."
                                        active: true
                                        verified: false
                                        role: "MEMBER"
                                        taaruf_status: "CLOSE"
                                      - id: "591c6b44-9331-4fa0-95a5-1dddc617a033"
                                        email: "jo..."
                                        firstname: "Jo..."
                                        lastname: "Do..."
                                        active: false
                                        verified: true
                                        role: "MEMBER"
                                        taaruf_status: "OPEN"
        patch:
            tags:
            - User
            description: User can only update himself, for all roles
            requestBody:
                required: true
                content:
                    multipart/form-data:
                        schema:
                            type: object
                            properties:
                                firstname:
                                    type: string
                                lastname:
                                    type: string
                                avatar:
                                    type: string
                                    format: binary
            responses:
                200:
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: object
                                $ref: "#/components/schemas/user"
                            examples:
                                complete-data:
                                    $ref: "#/components/examples/complete-data"
                                no-avatar:
                                    $ref: "#/components/examples/no-avatar"
                401:
                    description: Unauthorized
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    error:
                                        type: string
                                        example: Unauthorized
                                    statusCode:
                                        type: number
                                        example: 401
                403:
                    description: Forbidden
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    error:
                                        type: string
                                        example: Forbidden
                                    statusCode:
                                        type: number
                                        example: 403
                404:
                    description: Not Found
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    error:
                                        type: string
                                        example: Not Found
                                    statusCode:
                                        type: number
                                        example: 404
    "/users/:id":
        get:
            tags:
            - User
            description: Get by id - user role as MEMBER
            responses:
                200:
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: object
                                $ref: "#/components/schemas/user"
                            examples:
                                complete-data:
                                    $ref: "#/components/examples/complete-data"
                                no-avatar:
                                    $ref: "#/components/examples/no-avatar"
                401:
                    description: Unauthorized
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    error:
                                        type: string
                                        example: Unauthorized
                                    statusCode:
                                        type: number
                                        example: 401
                403:
                    description: Forbidden
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    error:
                                        type: string
                                        example: Forbidden
                                    statusCode:
                                        type: number
                                        example: 403
    "/users/activate/:id":
        patch:
            tags:
            - User
            responses:
                204:
                    description: OK. No Content
                401:
                    description: Unauthorized
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    error:
                                        type: string
                                        example: Unauthorized
                                    statusCode:
                                        type: number
                                        example: 401
                403:
                    description: Forbidden
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    error:
                                        type: string
                                        example: Forbidden
                                    statusCode:
                                        type: number
                                        example: 403
                404:
                    description: Not Found
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    error:
                                        type: string
                                        example: Not Found
                                    statusCode:
                                        type: number
                                        example: 404
    "/users/deactivate/:id":
        patch:
            tags:
            - User
            responses:
                204:
                    description: OK. No Content
                401:
                    description: Unauthorized
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    error:
                                        type: string
                                        example: Unauthorized
                                    statusCode:
                                        type: number
                                        example: 401
                403:
                    description: Forbidden
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    error:
                                        type: string
                                        example: Forbidden
                                    statusCode:
                                        type: number
                                        example: 403
                404:
                    description: Not Found
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    error:
                                        type: string
                                        example: Not Found
                                    statusCode:
                                        type: number
                                        example: 404
    "/users/change_password":
        patch:
            tags:
            - User
            description: Change password for all user role
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                password:
                                    type: string
                                    format: password
                                confirm_password:
                                    type: string
                                    format: password
            responses:
                204:
                    description: OK. No Content
                400:
                    description: Bad Request
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    message:
                                        type: string
                                        example: Password confirm is not match
                                    error:
                                        type: string
                                        example: Bad Request
                                    statusCode:
                                        type: number
                                        example: 400
                401:
                    description: Unauthorized
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    error:
                                        type: string
                                        example: Unauthorized
                                    statusCode:
                                        type: number
                                        example: 401
    "/users/profile":
        get:
            tags:
            - User
            description: Get by login user
            responses:
                200:
                    description: OK
                    content:
                        application/json:
                            schema:
                                type: object
                                $ref: "#/components/schemas/user"
                            examples:
                                profile-data:
                                    $ref: "#/components/examples/profile-data"
                401:
                    description: Unauthorized
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    error:
                                        type: string
                                        example: Unauthorized
                                    statusCode:
                                        type: number
                                        example: 401
                403:
                    description: Forbidden
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    error:
                                        type: string
                                        example: Forbidden
                                    statusCode:
                                        type: number
                                        example: 403
components:
    schemas:
        user:
            type: object
            properties:
                id:
                    type: string
                    example: 591c6b44-9331-4fa0-95a5-1dddc617a033
                email:
                    type: string
                    example: joh...
                firstname:
                    type: string
                    example: Joh...
                lastname:
                    type: string
                    example: Doe...
                active:
                    type: boolean
                    example: true
                verified::
                    type: boolean
                    example: true
                avatar:
                    type: string
                    example: /avatar/myavatar.jpg
                avatar_md:
                    type: string
                    example: /avatar/myavatar.jpg
                role:
                    type: string
                    example: MEMBER
                taaruf_status:
                    type: string
                    example: OPEN
                taaruf_open_at:
                    type: string
                    format: date-time
                    example: 2024-03-12T10:30:00Z
    examples:
        profile-data:
            summary: profile-data
            value:
                id: "591c6b44-9331-4fa0-95a5-1dddc617a033"
                email: "john_doe@gmail.com"
                firstname: "John"
                lastname: "Doe"
                active: true
                verified: true
                avatar: "/public/profile/avatar.jpg"
                avatar_md: "/public/profile/avatar_md.jpg"
                role: "MEMBER"
                taaruf_status: "BLOCKED"
        complete-data:
            summary: complete-data
            value:
                id: "591c6b44-9331-4fa0-95a5-1dddc617a033"
                email: "jo..."
                firstname: "Jo..."
                lastname: "Do..."
                active: true
                verified: true
                role: "MEMBER"
                taaruf_status: "BLOCKED"
        no-avatar:
            summary: no-avatar
            value:
                id: "591c6b44-9331-4fa0-95a5-1dddc617a033"
                email: "jo..."
                firstname: "Jo..."
                lastname: "Doe"
                active: true
                verified: true
                role: "MEMBER"
                taaruf_status: "BLOCKED"
        user:
            summary: user
            value:
                id: "591c6b44-9331-4fa0-95a5-1dddc617a033"
                email: "jo..."
                firstname: "Jo..."
                lastname: "Do..."
                active: true
                verified: false
                role: "MEMBER"
                taaruf_status: "BLOCKED"
